name: Schedule Lab Reset

on:
  workflow_call:
    inputs:
      workflowId:
        description: "The ID of the caller workflow"
        required: true
        type: string


permissions: write-all

jobs:
  prepare-matrix:
    name: Enqueue Lab Reset Workflow And Awaiting Result...
    runs-on: windows-latest
    steps:
    - name: Enqueue job, Await Result
      run: |
        $headers = @{
          "Accept" = "application/vnd.github+json"
          "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"
          "X-GitHub-Api-Version" = "2022-11-28"
        }
        $url = "https://api.github.com/repos/microsoft/netperf/dispatches"
        Write-Host "Dispatching with assigned runner: $assigned_runner"
        $body = @{
          event_type = "run-auto-reset-parent-or-child-lab-machine"
          client_payload = @{
            workflow_id = "${{ inputs.workflowId }}"
          }
        } | ConvertTo-Json
        Write-Host "Dispatching with body: $body"
        try {
          Invoke-WebRequest -Uri $url -Headers $github_headers -Method Post -Body $body
        } catch {
          Write-Host "[DispatchCallee] Failed to dispatch callee: $_"
          exit 1
        }

        for ($attempts = 0; $attempts -lt 36; $attempts++) {
          # TODO: Check if the callee workflow has completed.
        }

      shell: pwsh
